### ISSUE TITLE
Improve test suite

### ISSUE THREAD

**Issue by jubnzv** [nowarp/misti#162]
We could improve the test suite in the following way:
* [x] Add the `test/detectors/` directory containing tests in the following format: `<detector-name>tact`. Thus, we can enable only the specified detectors, reducing noise from other detectors and speeding up the execution time.
* [ ] ~~Handle `// Bad` comments. We might assume that the warnings are valid if and only if they are raised in the line containing this comment. This will simplify testing the test results, because sometimes we could miss a regression by simply running tests with `BLESS` without checking the expected output file.~~
* [x] Add specific directories to test dump-tools. We need to reduce the amount of files under the testing, since these tests are too slow.
* [x] Add tests for `DumpImport` outputs

To implement this, it would be enough to use regex and string functions in TypeScript, so there is no need to parse comments.

**Comment by jubnzv** [comment]
>  The first line should be a comment describing the detectors enabled for this file, e.g.:

Another option could be to create a `test/detectors` directory containing one test contract for each detector, named exactly after the detector.
