### ISSUE TITLE
Generic Soufflé bindings library

### ISSUE THREAD

**Issue by byakuren-hijiri** [nowarp/misti#3]
The Soufflé bindings and the related tests should be moved to a separate library available in NPM. This will enable to reuse it by other users.

Dependencies:
* [x] #27
* [x] #75 
* [x] Add tests for the new Souffle library, including sync and async executors. Use simple generic examples, e.g. some toy language, for testing.
* [x] Add examples
* [x] Create README
* [x] Move logic related to #8 to the `misti` repository
* [x] Rewrite paths and error messages making them customizable
* [x] Use the logger interface within the new bindings repo
* [x] Add custom exceptions to the library and handle them properly in Misti
* [x] Create a new repo and move other issues labeled `area:souffle` there
