### ISSUE TITLE
FunC frontend

### ISSUE THREAD

**Issue by byakuren-hijiri** [nowarp/misti#56]
Below is an incomplete list of tasks required to implement the initial FunC support. This will allow us to create AST detectors and establish an API that we will later use to transform this into the IR supporting both Tact and FunC (#74).

* ~~[ ] Merge https://github.com/tact-lang/tact/pull/559: Introduces the FunC parser which is capable to parse about 95% of FunC grammar. We have this limitation since FunC has a context-sensitive grammar.~~
* [x] Create AST that tracks code position and provides more convenient representation of FunC (no expr precedence hell, more sane representation of some nodes)
* [x] Parse it using the existing tree-sitter parser and convert it to the AST
* [ ] Add the AST utilities module (like for Tact)
* [ ] Create common interfaces for Tact and Func
  + [ ] Support AST detectors for FunC
* [ ] Support multi-language projects
  + [ ] Func imports from Tact files (see: https://docs.tact-lang.org/book/import#import-func-code)
* [ ] Func tools
  + [ ] AST dump

**Comment by jubnzv** [comment]
The FunC frontend was implemented using a different tool (to be announced later).
