### ISSUE TITLE
Design the IR

### ISSUE THREAD

**Issue by jubnzv** [nowarp/misti#74]
Design a new IR that expresses the runtime semantics of both: FunC and Tact.

This involves:
* [x] Designing an IR, choosing the more suitable features properties needed for analysis e.g.:
  - should it be SSA or something else?
  - do we need def-use chains or other spa information (#188)?
  - do we need an explicit dominance relation?
  - do we need access to TVM assembly?
  - etc.
* [ ] Add the mechanism to access high-level IR structure from which that structure has been generated which is required to get more context.
* [ ] Develop lowering passes from both: Tact and FunC high level IRs
  + [ ] Tact requires lowering for high-level constructions like contracts, traits and messages. The lowering should be kind of similar to the implementation of the Tact FunC backend.
  + [ ] Augmented assignments in both languages should be lowered
  + [ ] Tact functions/receivers/init functions should be lowered to the same function type
  + [ ] Correspondence IR <--> FunC/Tact AST 
* [ ] Design an API to access IR entries in the most convenient way.

Finally, it will give the possibility to write language-independent analyzers that work on a lower level than FunC/Tact.

**Comment by jubnzv** [comment]
The SSA-based IR that resembles TVM semantics was implemented using a different tool (to be announced later).
